/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 21 02:33:10 GMT 2019
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MessageBuilder_ESTest extends MessageBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("b>");
      assertEquals("Hello b>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("Yw B");
      assertEquals("Hello Yw B", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("1`#\"nowp%;\"7I0+UT.");
      assertEquals("Too long: 1`#\"nowp%;\"7I0+UT.", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      String string0 = messageBuilder0.getMessage("");
      assertEquals("Please provide a name!", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MessageBuilder messageBuilder0 = new MessageBuilder();
      // Undeclared exception!
      try { 
        messageBuilder0.getMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }
}
